name: Bug Report
description: Report a bug to help us improve The Diary
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug! This helps us improve The Diary for all users.
        
        Before submitting, please check if this issue has already been reported.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what happened!
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Tell us how to reproduce this bug
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: I expected...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Instead, what happened was...
    validations:
      required: true

  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Opera
        - Other

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of The Diary are you running?
      placeholder: e.g., v1.0.0

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Please provide details about your environment:
      value: |
        - OS: [e.g. Windows 11, macOS 13, Ubuntu 22.04]
        - Browser: [e.g. Chrome 118, Firefox 119]
        - Node.js version: [e.g. 18.17.0]
        - Device: [e.g. Desktop, Mobile - iPhone 14]
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Log Output
      description: Please copy and paste any relevant log output (check browser console for errors)
      render: shell

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I have searched for existing issues that might be related to this bug
          required: true
        - label: I have provided all the requested information
          required: true
        - label: I agree to follow this project's Code of Conduct
          required: true